### ISSUE TITLE
Maven dependency for yaml module has a misstype

### ISSUE THREAD

**Issue by Tomasan7** [MrIvanPlays/AnnotationConfig#5]
Hi, I was trying to add a maven dependency for the yaml module, but maven didn't want to resolve the dependency for some reason.

After some investigation, I noticed, that the actual dependency artifactId is called `annotationconfg-yaml` instead of `annotationconfig-yaml` (missing 'i' in "config")
Would be nice to fix :D

**Comment by MrIvanPlays** [comment]
wow that typo exists since the library was created.. jeez

anyways, i will find time to fix it. thanks for spotting it tho
